language: go

go:
  - tip
  - 1.14
  - 1.13
os:
  - linux
  - osx

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic -race

after_success:
  - bash <(curl -s https://codecov.io/bash)
