name: Build & test

on:
  push:
    branches: [ master ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v -coverprofile=coverage.txt -covermode=atomic -bench .

    - name: CodeCov
      uses: codecov/codecov-action@v2
      with:
        files: coverage.txt